### ISSUE TITLE
Using ModelSaver

### ISSUE THREAD

**Issue by andriusdc** [PIQuIL/QuCumber#106]
Hi ! I am trying to use some saved models by the ModelSaver callback, but I am not sure on how to load then for future use and I didn't find on the documentation how to do it.  How can I do it ? I saved then using this command:

```
callbacks = [
    metric_eval,
    ModelSaver(1, folder_path, 'modelo ' , save_initial=True, metadata=None, metadata_only=False)
]  
```
Is it the correct way to save it by the way?

**Comment by emerali** [comment]
The way you've set it up now, it'll save once every epoch, to the file `modelo `, meaning it'll overwrite the same file every epoch. This might be what you want. But if you want to save to different files every epoch, you should pass something like: `modelo_{}`, this is a format string with one blank (the {}) which will be replaced with the epoch number or the word "initial" depending on what stage of training you're at. 

To load up the model from a file, you'd need to know what type of quantum state you trained.
Say for example, you trained a `PositiveWaveFunction`, you'd use this command to reload the model from the file:

```
model = PositiveWaveFunction.autoload(file_path)
```
