### ISSUE TITLE
Investigate Speed Regression in ComplexWavefunction training

### ISSUE THREAD

**Issue by emerali** [PIQuIL/QuCumber#50]
ComplexWavefunction training seems to have gotten much slower after the restructuring.

Profiled training (on my laptop's GPU) of a ComplexWavefunction on 2qubit data for 300 epochs, k=1, pos_batch_size=50, neg_batch_size=10, lr=0.01, and computing fidelity and KL every 50 epochs. The results can be found here: https://gist.github.com/emerali/1a18e76f39b6e394208247c5e2cedc1e

2qubits_training_prun contains the results of profiling the current implementation (commit hash: 901b3ce)

2qubits_training_prun_old contains the results of profiling the old implementation (commit hash: c38b1db)

**Comment by mbeach42** [comment]
I think this might be a GPU issue. The new version script takes only about 500 seconds (8.3 min) on my laptop.

**Comment by emerali** [comment]
k, i ran this again on CPU, same training parameters, results are here: https://gist.github.com/emerali/1a3b64693f794f14e79aed4baa3ed299

2qubits_ ... _current is going off of commit hash 2c40115 (which should be the same as 901b3ce)

2qubits_..._master is going off of commit hash c38b1db

**Comment by emerali** [comment]
it looks like the for loop over the Hilbert sub-space is embarrassingly parallel:

https://github.com/PIQuIL/QuCumber/blob/a69595ddce8496dcee65fb3ff3ab6f4050a76450/qucumber/nn_states/complex_wavefunction.py#L178

it may be possible to use [multiprocessing](https://pytorch.org/docs/stable/notes/multiprocessing.html) to speed this up
