### ISSUE TITLE
Use native pytorch complex type

### ISSUE THREAD

**Issue by Roger-luo** [PIQuIL/QuCumber#53]
We will have an experimental support for native complex type in pytorch (https://github.com/pytorch/pytorch/issues/755), which would result in some performance improvements and code quality improvements for free. 

The CPU part will be implemented based on my previous effort (in short term): https://github.com/Roger-luo/pytorch/tree/complex-cpu-backend/aten/src/THZ

The following work will be done in a new repo (which will be move to pytorch.org's repo later): https://github.com/Roger-luo/THZ

as a plugin based on new plugin interface: https://github.com/pytorch/pytorch/pull/11216

Further discussion can be found in pytorch's slack channel: complex-numbers (send an email for invitation first).

**Comment by lamhoson** [comment]
Any suggestion for latest complex tensor module to be used in PyTorch ? I need one to handle my research works for complex numbers.

**Comment by Roger-luo** [comment]
@lamhoson https://github.com/pytorch/pytorch/issues/755

**Comment by Roger-luo** [comment]
- [ ] use native scalar mult (2x faster)

```
In [7]: %timeit scalar_mult(A, B)
83.2 ms ± 1.04 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [8]: cA.dtype
Out[8]: torch.complex128

In [9]: cB = torch.zeros(1000, 1000, dtype=torch.complex128)

In [10]: %timeit cA * cB
43.8 ms ± 462 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

**Comment by lamhoson** [comment]
Would complex data-type release with coming PyTorch version 1.0's formal release ?


发自网易邮箱 iPhone 版
On 9/18/2018 04:17，Rogerluo<notifications@github.com> wrote：
use native scalar mult (2x faster)
In [7]: %timeit scalar_mult(A, B)
83.2 ms ± 1.04 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [8]: cA.dtype
Out[8]: torch.complex128

In [9]: cB = torch.zeros(1000, 1000, dtype=torch.complex128)

In [10]: %timeit cA * cB
43.8 ms ± 462 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
