### ISSUE TITLE
Occasional NaN values when estimating energy for a TFIM chain

### ISSUE THREAD

**Issue by emerali** [PIQuIL/QuCumber#60]
Seems to happen for large systems (i've only seen it happen for N=512, but i haven't played around with it too much yet)

**Comment by Roger-luo** [comment]
Any MWE?

**Comment by emerali** [comment]
I'll send one to you later this week since I'm gonna be fairly busy the next couple days

**Comment by mbeach42** [comment]
This is probably fixed in develop with the KL log(x+eps) thing. Can we close this now?

**Comment by Roger-luo** [comment]
This is fixed. I forget to close the issue.
