### ISSUE TITLE
Jupyter tutorials don't render on GitHub

### ISSUE THREAD

**Issue by rgmelko** [PIQuIL/QuCumber#62]
WTF is that?  Only tutorial 1 renders properly on the master branch

**Comment by Roger-luo** [comment]
Works well on GHERKIN.

**Comment by mbeach42** [comment]
Can't reproduce. On chrome version 69.0 they seems to render perfectly.

**Comment by Roger-luo** [comment]
I think this is just a GitHub issue. But we should support https://mybinder.org, there is awesome for browsing notebooks.

**Comment by emerali** [comment]
I've actually already setup mybinder support. In the documentation, there's a link at the top of each rendered jupyter notebook.

example: https://qucumber.readthedocs.io/en/stable/_examples/Tutorial1_TrainPosRealWavefunction/tutorial_quantum_ising.html

also, the jupyter notebooks load fine for me thru github (i'm using firefox)

**Comment by Roger-luo** [comment]
I see. That's nice. I'll close this, since this is not our problem.
