### ISSUE TITLE
Tensor Network feature request

### ISSUE THREAD

**Issue by akshat998** [PIQuIL/QuCumber#72]
I would like to integrate tensor networks capable of:

* Producing samples that can be used by the existing RBM for training. The tensor network shall 
   be implemented for :
    * POVM Types : Pauli-4, Pauli, Terta, Trine, Psi-2
    * MPS Types    : GHZ (along with the option of reading MPS from user-provided files)
    * N qubits
    * With the option of adding local noise

* A tensor networks capable of evaluating quantum fidelity for large qubit systems based on the 
   number of samples

The proposal is based on the paper: [Reconstructing quantum states with generative models
](https://arxiv.org/abs/1810.10584)
And is being implemented under the guidance of Dr. Juan Carrasquilla

**Comment by Roger-luo** [comment]
I don't think this will goes into QuCumber. We have a (work in progress) package here: 

https://github.com/MelkoCollective/Pepinillo 

Please feel free to file us an issue there.

**Comment by rgmelko** [comment]
Currently we keep the sampling codes separate from the reconstruction codes.  For example, Dan's iTensor-based sampling code for his QuCumber study is here:

https://github.com/MelkoCollective/SourKRAUT

We should discuss whether the POVM-based sampling goes under SourKRAUT or Pepinillo.  My preference would be SourKRAUT I think.
