### ISSUE TITLE
Learning a Density Matrix

### ISSUE THREAD

**Issue by andriusdc** [PIQuIL/QuCumber#87]
Is it possible to change the code so it works with density matrices of mixed states ? I wanna to use QuCumber on the lab but pure state is not achievable there.

**Comment by mbeach42** [comment]
Hi @andriusdc,
Currently, QuCumber only supports pure states. One method to extend to mixed states is demonstrated in  [1801.09684](https://arxiv.org/abs/1801.09684) by learning a purification of the mixed state. Unfortunately, this has not found its way into QuCumber as of yet.

**Comment by emerali** [comment]
Hello!

Density Matrix tomography is now supported, please upgrade QuCumber to version 1.3 and check out the new tutorial to learn how to use it.
