### ISSUE TITLE
Error with the unitaries dictionary

### ISSUE THREAD

**Issue by andriusdc** [PIQuIL/QuCumber#90]
I am using Qucumber to reconstruct a experimental CHSH protocol wavefunction, but I am having some troubles. The first one happens when my txt with the qubits basis that I measured don't contains any measurement on "Z Z" basis ( working with 2-qubits). The error is this one:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-58215aa8cfb1> in <module>
     73     lr=lr,
     74     input_bases=train_bases,
---> 75     callbacks=callbacks,
     76 )
     77 

~/anaconda3/envs/Projeto/lib/python3.6/site-packages/qucumber/nn_states/complex_wavefunction.py in fit(self, data, epochs, pos_batch_size, neg_batch_size, k, lr, input_bases, progbar, starting_epoch, time, callbacks, optimizer, **kwargs)
    280                 callbacks=callbacks,
    281                 optimizer=optimizer,
--> 282                 **kwargs
    283             )
    284 

~/anaconda3/envs/Projeto/lib/python3.6/site-packages/qucumber/nn_states/wavefunction.py in fit(self, data, epochs, pos_batch_size, neg_batch_size, k, lr, input_bases, progbar, starting_epoch, time, callbacks, optimizer, **kwargs)
    508                 train_samples,
    509                 input_bases,
--> 510                 z_samples,
    511             )
    512             callbacks.on_epoch_start(self, ep)

~/anaconda3/envs/Projeto/lib/python3.6/site-packages/qucumber/nn_states/wavefunction.py in _shuffle_data(self, pos_batch_size, neg_batch_size, num_batches, train_samples, input_bases, z_samples)
    388                 z_samples.shape[0],
    389                 size=(num_batches * neg_batch_size,),
--> 390                 dtype=torch.long,
    391             )
    392             shuffled_neg_samples = z_samples[neg_batch_perm]

RuntimeError: invalid argument 2: max must be greater than min, but got: min = 0, max = 0 at /pytorch/aten/src/TH/generic/THTensorRandom.cpp:40
```

The second one, is about the unitaries that I need do apply on the original wavefunction to rotate it. My dictionary is the following:
```
Ux = torch.tensor ([[[np.divide(1,np.sqrt(2)),np.divide(1,np.sqrt(2))],[np.divide(1,np.sqrt(2)),-np.divide(1,np.sqrt(2))]], np.zeros((2,2))], dtype=torch.double)
Uz = torch.tensor ([np.identity(2),np.zeros((2,2))], dtype=torch.double)
Ua = torch.tensor ([np.real(Ry(-45)), np.imag(Ry(-45))], dtype=torch.double)
Ub = torch.tensor ([np.real(Ry(45)), np.imag(Ry(45))], dtype=torch.double)
                    
unitary_dict = unitaries.create_dict(Z=Uz,X=Ux, A=Ua, B=Ub)
```
So I get a error which apparently seems to be because the package don't recognize my unitaries names "A" and "B". Here is the error:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-3-d8490c311792> in <module>
     73     lr=lr,
     74     input_bases=train_bases,
---> 75     callbacks=callbacks,
     76 )
     77 

~/anaconda3/envs/Projeto/lib/python3.6/site-packages/qucumber/nn_states/complex_wavefunction.py in fit(self, data, epochs, pos_batch_size, neg_batch_size, k, lr, input_bases, progbar, starting_epoch, time, callbacks, optimizer, **kwargs)
    280                 callbacks=callbacks,
    281                 optimizer=optimizer,
--> 282                 **kwargs
    283             )
    284 

~/anaconda3/envs/Projeto/lib/python3.6/site-packages/qucumber/nn_states/wavefunction.py in fit(self, data, epochs, pos_batch_size, neg_batch_size, k, lr, input_bases, progbar, starting_epoch, time, callbacks, optimizer, **kwargs)
    530                     break
    531 
--> 532             callbacks.on_epoch_end(self, ep)
    533             if self.stop_training:  # check for stop_training signal
    534                 break

~/anaconda3/envs/Projeto/lib/python3.6/site-packages/qucumber/callbacks/callback_list.py in on_epoch_end(self, rbm, epoch)
     73     def on_epoch_end(self, rbm, epoch):
     74         for cb in self.callbacks:
---> 75             cb.on_epoch_end(rbm, epoch)
     76 
     77     def on_batch_start(self, rbm, epoch, batch):

~/anaconda3/envs/Projeto/lib/python3.6/site-packages/qucumber/callbacks/metric_evaluator.py in on_epoch_end(self, nn_state, epoch)
    130             metric_vals_for_epoch = {}
    131             for metric_name, metric_fn in self.metrics.items():
--> 132                 val = metric_fn(nn_state, **self.metric_kwargs)
    133                 metric_vals_for_epoch[metric_name] = val
    134 

~/anaconda3/envs/Projeto/lib/python3.6/site-packages/qucumber/utils/training_statistics.py in KL(nn_state, target_psi, space, bases, **kwargs)
    201         num_bases = len(bases)
    202         for b in range(1, len(bases)):
--> 203             psi_r = rotate_psi(nn_state, bases[b], space, unitary_dict)
    204             target_psi_r = rotate_psi(
    205                 nn_state, bases[b], space, unitary_dict, target_psi

~/anaconda3/envs/Projeto/lib/python3.6/site-packages/qucumber/utils/training_statistics.py in rotate_psi(nn_state, basis, space, unitaries, psi)
     93             U = torch.tensor([1.0, 0.0], dtype=torch.double, device=nn_state.device)
     94             for ii in range(num_nontrivial_U):
---> 95                 tmp = unitaries[basis[nontrivial_sites[ii]]]
     96                 tmp = tmp[
     97                     :, int(space[x][nontrivial_sites[ii]]), int(v[nontrivial_sites[ii]])

KeyError: 'A'
```
Does anyone knows why this happens? Am I doing something wrong ?

**Comment by mbeach42** [comment]
Hi @andriusdc 

I believe QuCumber needs measurements in the Z-Z basis. You may have to adjust the definitions of your pauli meaurements (X,Y,Z) so that at least 1 set of measurements is in the references basis ZZ. It may be inconvenient, but it's possible.

Regarding the unitaries, I assume the problem is not in the `unitary_dict` function since your error message seems to be from the `callbacks` when training the RBM. Can you please post the full error message? I will look at this more tomorrow.

**Comment by andriusdc** [comment]
Thanks for your help. The thing is that I measured on the lab the basis Z and X on the first qubit, and Z+X and Z-X on the second, so I can't change my basis so I can get some Z-Z measurement, cause I didn't measured the same operator on both qubits. Is it really impossible to avoid that measurement in the Z-Z basis ? Can't I declare to the package that my wavefunction is on another basis ?
About the second error, the message that I posted is the complete error message. I believe that the error is on the dictionary because it works if I change the keyword A to Y. If the unitaries are declared as X,Y,Z, it works, regardless of how those matrix are defined. The thing is that I need more than 3 unitaries, and when I pick any letter for naming that fourth one, I get that KeyError.

**Comment by mbeach42** [comment]
Regarding (2), Can you confirm that the following code gives no error? 

```Ux = torch.tensor ([[[np.divide(1,np.sqrt(2)),np.divide(1,np.sqrt(2))],[np.divide(1,np.sqrt(2)),-np.divide(1,np.sqrt(2))]], np.zeros((2,2))], dtype=torch.double)
Uz = torch.tensor ([np.identity(2),np.zeros((2,2))], dtype=torch.double)
Ua = torch.tensor ([np.real(Ry(-45)), np.imag(Ry(-45))], dtype=torch.double)
Ub = torch.tensor ([np.real(Ry(45)), np.imag(Ry(45))], dtype=torch.double)
                    
unitary_dict = unitaries.create_dict(Z=Uz,X=Ux, A=Ua, B=Ub)
```

This runs fine on my computer. I assume the error is when you try 
```
nn_state.fit(
    train_samples,
    epochs=epochs,
    pos_batch_size=pbs,
    neg_batch_size=nbs,
    lr=lr,
    k=k,
    input_bases=train_bases,
    callbacks=callbacks,
)
```
Is that correct?

**Comment by andriusdc** [comment]
Yes, it is right there. I didn't made myself clear, my bad, but I think that the problem is not with the use of the unitaries.create_dict() function, but when the code interprets it.

**Comment by emerali** [comment]
could you post your `train_bases` file? it might help with debugging this issue

**Comment by andriusdc** [comment]
Sure! The first line is only there to avoid the Z basis problem. Here is my basis text:

`Z Z
X A
X B
Z A
Z B'

The other basis txt are only those entries repeated for more lines that I can post here. Here is the print:

**Comment by emerali** [comment]
Just a couple more sanity checks:
1. Make sure you're passing the correct `unitary_dict` when creating the `ComplexWaveFunction` object
2. `train_bases` should have the same number of lines as the number of measurements. I'm guessing you're just showing the list of unique bases? (this is fine for diagnostic purposes, I'm just making sure you're passing the right thing to the right parts of the program)

As for the first error message you were getting, I still need to think about that one some more.

**Comment by andriusdc** [comment]
1-Check.
2-Check. I showed only the list of unique basis because it wont fit here all the measurements lines.

**Comment by emerali** [comment]
Ahh, I believe I've found the cause of the second issue, it seems like you're using an out of date version of QuCumber. The version you're using likely has this line in the code for computing the KL divergence:

https://github.com/PIQuIL/QuCumber/blob/v1.1.0/qucumber/utils/training_statistics.py#L180

Whereas in newer versions, this issue was resolved:

https://github.com/PIQuIL/QuCumber/blob/v1.2.1/qucumber/utils/training_statistics.py#L179

Please try updating QuCumber either using `pip install -U qucumber` or the conda equivalent, and see if that helps.

**Comment by emerali** [comment]
Update: I've found another bug in the KL divergence code which I'm trying to fix right now.

**Comment by emerali** [comment]
Just to follow up, can you confirm whether QuCumber version 1.2.2 fixed the issue you were having?

**Comment by andriusdc** [comment]
I just tested and it works ! Thank you so much for your help. QuCumber is making my lab research so much easier. Thank you all!

**Comment by emerali** [comment]
No problem!

Glad to hear you find QuCumber useful :smile:
