### ISSUE TITLE
Problem with EarlyStopping

### ISSUE THREAD

**Issue by andriusdc** [PIQuIL/QuCumber#91]
Hello ! i am trying to use qucumber.callbacks.EarlyStopping class, but I am having some troubles with it. Here is the part of my code where I call it:

```
 callbacks = [
        MetricEvaluator(
            log_every,
            {"Fidelity": ts.fidelity, "KL":ts.KL, "Coef":psi_coefficient},
            target_psi=true_psi,
            bases=bases,
            verbose=True,
            space=space,       
        ),
        EarlyStopping(
            1, 0.01, 10, MetricEvaluator(1,{"KL":ts.KL}), "KL", "absolute")
    ]   
```

But I am getting this error:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-62-1830212e8c65> in <module>
     71         ),
     72         EarlyStopping(
---> 73             1, 0.01, 10, MetricEvaluator(1,{"KL":ts.KL}), "KL", "absolute")
     74     ]   
     75 

~\Anaconda3\envs\Andrius\lib\site-packages\qucumber\callbacks\early_stopping.py in __init__(self, period, tolerance, patience, evaluator_callback, quantity_name, criterion)
     89             self.value_getter = self.evaluator_callback.get_value
     90 
---> 91             if criterion == self._convergence_criteria[2]:
     92                 raise TypeError(
     93                     "Can't use a variance based convergence criterion "

AttributeError: 'EarlyStopping' object has no attribute '_convergence_criteria'
```

Am I doing something the wrong way ?

**Comment by emerali** [comment]
Hi, sorry for the delay, I've fixed the relevant bug, so try updating QuCumber and running your code again.

One error I did notice in your code, however, is in this snippet:
`MetricEvaluator(1,{"KL":ts.KL})`

You are missing a few keyword arguments that are needed for `ts.KL` (see the docs [here](https://qucumber.readthedocs.io/en/stable/training_statistics.html)), like `space`, `target_psi`, etc. You need to pass these through `MetricEvaluator` as you did further up in your code. The proper call should be something like this:

```
MetricEvaluator(1, {"KL":ts.KL}, target_psi=true_psi, bases=bases, space=space)
```

However, I'm not sure why you want to create *another* `MetricEvaluator` object when you've already created one earlier, you could just assign the first one to a variable and pass it to `EarlyStopping`, like so:

```
metric_eval = MetricEvaluator(
    1,
    {"Fidelity": ts.fidelity, "KL":ts.KL, "Coef":psi_coefficient},
    target_psi=true_psi,
    bases=bases,
    verbose=True,
    space=space,       
)
callbacks = [
    metric_eval,
    EarlyStopping(1, 0.01, 10, metric_eval, "KL", "absolute")
]  
```

**Comment by andriusdc** [comment]
Hello again ! Thanks for your help. I've tried to run my code after updating Qucumber and writing the callbacks as you did on the last code you posted here, but it still gives me same bug.

**Comment by emerali** [comment]
The stack trace must have changed though, as the section of code which caused it is different now.

Could you send the exact stack trace you get?

**Comment by andriusdc** [comment]
It seems like the stack trace is the same:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-bab7826727f7> in <module>
     79     callbacks = [
     80         metric_eval,
---> 81         EarlyStopping(1, 0.01, 10, metric_eval, "KL", "absolute")
     82     ]  
     83 

~/anaconda3/envs/Projeto/lib/python3.6/site-packages/qucumber/callbacks/early_stopping.py in __init__(self, period, tolerance, patience, evaluator_callback, quantity_name, criterion)
     89             self.value_getter = self.evaluator_callback.get_value
     90 
---> 91             if criterion == self._convergence_criteria[2]:
     92                 raise TypeError(
     93                     "Can't use a variance based convergence criterion "

AttributeError: 'EarlyStopping' object has no attribute '_convergence_criteria'

**Comment by emerali** [comment]
Are you sure you're using the latest version of QuCumber? Sometimes pip is a bit unclear so try running 
```
import qucumber
print(qucumber.__version__)
```
in python. The latest version is 1.2.3

**Comment by andriusdc** [comment]
Oh, just checked this, my Qucumber version is 1.2.2. Is there anyway to install it without pip ? I've triyed to clone the git hub folder as the Piquill page says to, but it gives me this error:

fatal: destination path 'QuCumber' already exists and is not an empty directory.

**Comment by emerali** [comment]
try `pip install -U qucumber`

**Comment by emerali** [comment]
it depends on which model file you provide the `file_path` for
